//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SussexCompanions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingHistory
    {
        public long BillingHistoryId { get; set; }
        public System.DateTime BillingHistoryDate { get; set; }
        public bool BillingHistoryIsPayed { get; set; }
        public double BillingHistoryAmount { get; set; }
        public bool BillingHistoryIsOverdue { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
