//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SussexCompanions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCategory
    {
        public int EventCategoryId { get; set; }
        public int EventId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Event Event { get; set; }
    }
}
