//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SussexCompanions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSchedule
    {
        public long MeetingScheduleId { get; set; }
        public string MeetingScheduleTitle { get; set; }
        public System.DateTime MeetingScheduleEndsOn { get; set; }
        public string MeetingScheduleRepeatCronExpression { get; set; }
        public int EventId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
