//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SussexCompanions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public int PaymentCardId { get; set; }
        public bool PaymentCardIsDefault { get; set; }
        public string PaymentCardHolderName { get; set; }
        public string PaymentCardNumber { get; set; }
        public System.DateTime PaymentCardExpireDate { get; set; }
        public string PaymentCardSecurityCode { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
