//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SussexCompanions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPersonality
    {
        public int UserPersonalityId { get; set; }
        public int UserId { get; set; }
        public int PersonalityId { get; set; }
    
        public virtual Personality Personality { get; set; }
        public virtual User User { get; set; }
    }
}
